const students = [
    { id: 1, name: "Ali Khan",          skills: ["React", "Node.js"],      score:85, city: "Hyderabad" },
    { id: 2, name: "Aanam Baig",        skills: ["Python", "ORC"],         score:85, city: "Delhi" },
    { id: 3, name: "Saniya Khan",       skills: ["Ai", "Ml"],              score:85, city: "Mumbai" },
    { id: 4, name: "Simran Sayaniya",   skills: ["React", "Node.js"],      score:85, city: "Nagpur" },
    { id: 5, name: "Aaryan Padole",     skills: ["Python"],                score:85, city: "Kolkatta" },
    { id: 6, name: "Farhan Raza",       skills: ["Data Science" ],         score:85, city: "Delhi" },
    { id: 7, name: "Arnav ",            skills: ["Data Analytics"],        score:85, city: "Punjab" },
    { id: 8, name: "Danish Rajwani",    skills: ["React", "Node.js"],      score:85, city: "Hyderabad" },
    { id: 9, name: "Taniya Sayaniya",   skills: ["Express.js"],            score:85, city: "Ajmer" },
    { id: 10, name: "Mansi Limbachiya", skills: ["Java"],                  score:85, city: "Mumbai" },
    { id: 11, name: "Faizan Kaliwala",  skills: ["Social Developer"],      score:85, city: "Nagpur" },
    { id: 12, name: "Sana Kaliwala",    skills: ["React.js"],              score:85, city: "Delhi" },
    { id: 13, name: "Soha Noorani",     skills: ["React", "Node.js"],      score:85, city: "Hyderabad" },
    { id: 14, name: "Ishan Kishan",     skills: ["JavaScript"],            score:85, city: "Pune" },
    { id: 15, name: "Rohit Sharma",     skills: ["Python"],                score:85, city: "Bangolore" },
    { id: 16, name: "Alal Hazrat",      skills: ["Ai"],                    score:85, city: "Mumbai" },
    { id: 17, name: "Mohammed Ali",     skills: ["Apex"],                  score:85, city: "Nagpur" },
    { id: 18, name: "Vaibav Suryavans", skills: ["Data Analysis", "SQL"],  score:85, city: "Delhi" },
    { id: 19, name: "Rehan Khan",       skills: ["React", "Node.js"],      score:85, city: "Hyderabad" },
    { id: 20, name: "Jannat Khan",      skills: ["React.js"],              score:85, city: "Pune" },
]